// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey']!,
    appId: dotenv.env['androidAppId']!,
    messagingSenderId: dotenv.env['androidMessagingSenderId']!,
    projectId: dotenv.env['androidProjectId']!,
    storageBucket: dotenv.env['androidStorageBucket']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['iOSApiKey']!,
    appId: dotenv.env['iOSAppId']!,
    messagingSenderId: dotenv.env['iOSMessagingSenderId']!,
    projectId: dotenv.env['iOSProjectId']!,
    storageBucket: dotenv.env['iOSStorageBucket']!,
    iosClientId: dotenv.env['iOSIosClientId']!,
    iosBundleId: dotenv.env['iOSIosBundleId']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['macOSApiKey']!,
    appId: dotenv.env['macOSAppId']!,
    messagingSenderId: dotenv.env['macOSMessagingSenderId']!,
    projectId: dotenv.env['macOSProjectId']!,
    storageBucket: dotenv.env['macOSStorageBucket']!,
    iosClientId: dotenv.env['macOSIosClientId']!,
    iosBundleId: dotenv.env['macOSIosBundleId']!,
  );
}
